vrc-get/vrc-get

src/commands.rs
src/version/version.rs
src/vpm/mod.rs

feat: search command

---

src/commands.rs

feat: add 'resolve' as alias of 'install'

---

.github/workflows/publish.yml
Cargo.toml
README.md

Publish for crates.io

---

README.md

chore(readme): add link to homebrew

---

README.md

Add very small description for each command 
Closes #44

chore: add small description for each command

---

src/commands.rs

fix: description of `vrc-get repo packages`

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/vpm/mod.rs

Fix: windows drive letter is not proceed

---

Cargo.lock
Cargo.toml
src/commands.rs
src/vpm/add_package.rs
src/vpm/mod.rs
src/vpm/structs.rs
src/vpm/utils.rs

Legacyfolder and confirm

---

src/commands.rs
src/vpm/add_package.rs
src/vpm/mod.rs
src/vpm/repo_holder.rs
src/vpm/structs.rs

2.1.0 support

---

src/commands.rs
src/vpm/mod.rs
src/vpm/repo_holder.rs

fix bad behaviour with package-cache.json

---

src/vpm/mod.rs
src/vpm/structs.rs

fix: error if value of legacyAssets is null

---

Cargo.lock
Cargo.toml
src/commands.rs

feat: initial commit for completion

---

src/version/mod.rs
src/version/range.rs
src/vpm/mod.rs
src/vpm/package_resolution.rs
src/vpm/structs.rs

feat: support version range notion in dependencies block

---

Cargo.lock
Cargo.toml

close #230 
close #231 (due to https://github.com/rustls/rustls/issues/33)

chore(deps): make rustls available

---

src/commands.rs
src/commands/info.rs
src/version/mod.rs
src/version/unity_version.rs
src/vpm/mod.rs
src/vpm/package_resolution.rs
src/vpm/structs.rs

Unity Version Support

---

Cargo.lock
Cargo.toml
src/version/actual_identifier.rs
src/version/identifier.rs
src/version/mod.rs
src/version/parsing_buf.rs
src/version/range.rs
src/version/segment.rs
src/version/version.rs

Use our semver impl instead of semver crate

Use our semver impl instead of semver crate

---

Cargo.lock
vrc-get-vpm/src/lib.rs
vrc-get-vpm/src/structs.rs
vrc-get/src/commands.rs
vrc-get/src/commands/info.rs

Yank version

---

Cargo.lock
vrc-get-vpm/src/lib.rs
vrc-get-vpm/src/repo_holder.rs
vrc-get/src/commands.rs

Override official repository

---

vrc-get-vpm/src/lib.rs

fix: downloading repositories / installing packages is not in parallel

---

vrc-get-vpm/Cargo.toml
vrc-get-vpm/src/add_package.rs
vrc-get-vpm/src/lib.rs
vrc-get-vpm/src/repo_holder.rs
vrc-get-vpm/src/version/identifier.rs
vrc-get-vpm/src/version/range.rs
vrc-get/Cargo.toml
vrc-get/src/commands.rs
vrc-get/src/commands/info.rs

chore: hide experimental features behind the feature flags

---

vrc-get-vpm/src/lib.rs
vrc-get-vpm/src/version/range.rs

fix: installing prerelease package from unlocked packages failure

---

Cargo.lock
vrc-get/Cargo.toml
vrc-get/src/commands.rs

Improve docs

---

vrc-get/src/commands.rs

fix(cli,upgrade): make package name optional

---

Cargo.lock
vrc-get-vpm/Cargo.toml
vrc-get-vpm/src/unity_project.rs
vrc-get-vpm/src/unity_project/migrate_unity_2022.rs
vrc-get-vpm/src/unity_project/pending_project_changes.rs
vrc-get-vpm/src/unity_project/upm_manifest.rs
vrc-get-vpm/src/version/unity_version.rs
vrc-get/Cargo.toml
vrc-get/src/commands.rs
vrc-get/src/commands/migrate.rs
vrc-get/src/main.rs

Migrate project

---

vrc-get-vpm/src/unity_project.rs
vrc-get-vpm/src/unity_project/pending_project_changes.rs
vrc-get-vpm/src/unity_project/resolve.rs

feat(vpm): support resolve template project

---

vrc-get-vpm/src/unity_project.rs
vrc-get-vpm/src/unity_project/remove_package.rs

fix: allow removing legacy packages

---

vrc-get/Cargo.toml

feat: add manifest for binstall

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.gitignore
Cargo.lock
vrc-get-vpm/Cargo.toml
vrc-get/Cargo.toml

Upgrade and restore aarch build

---

vrc-get-vpm/src/version/range.rs

fix: support for hyphen-less prerelease for a partial version

---

vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/environment/repo_holder.rs
vrc-get-vpm/src/environment/settings.rs
vrc-get-vpm/src/unity_project/upm_manifest.rs
vrc-get-vpm/src/unity_project/vpm_manifest.rs
vrc-get-vpm/src/utils/crlf_json_formatter.rs
vrc-get-vpm/src/utils/mod.rs

fix: LF is used for EOL character on windows instead of CRLF

---

.github/workflows/publish.yml

should fix https://github.com/anatawa12/vrc-get/actions/runs/7788154650

ci: do not update changelog with prerelease

---

.github/workflows/publish.yml

Should fix https://github.com/anatawa12/vrc-get/actions/runs/7788412601/job/21237750449

ci: do not use changelog with prereleases

---

CHANGELOG.md
vrc-get-vpm/src/environment.rs

fix: error until we add some repository

---

vrc-get-vpm/src/io/mod.rs
vrc-get-vpm/src/io/tokio.rs
vrc-get-vpm/src/unity_project.rs
vrc-get-vpm/src/unity_project/call_unity.rs

refactor: wrap process with io traits

---

vrc-get-vpm/src/io/mod.rs
vrc-get-vpm/src/io/tokio.rs
vrc-get-vpm/src/traits.rs

chore: unseal Io Traits

---

CHANGELOG.md
Cargo.lock
README.md
vrc-get-vpm/Cargo.toml
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/environment/project_management.rs
vrc-get-vpm/src/environment/settings.rs
vrc-get-vpm/src/io/mod.rs
vrc-get-vpm/src/io/tokio.rs
vrc-get-vpm/src/lib.rs
vrc-get-vpm/src/unity_project.rs
vrc-get-vpm/src/unity_project/project_type.rs
vrc-get-vpm/src/unity_project/vpm_manifest.rs
vrc-get/Cargo.toml
vrc-get/build.rs
vrc-get/build_target_info.rs
vrc-get/src/commands.rs
vrc-get/src/commands/vcc.rs

Project management

---

Cargo.lock
vrc-get-litedb/build.rs
vrc-get-litedb/src/bootstrapper.rs
vrc-get-litedb/src/connection.rs
vrc-get-litedb/src/lib.rs
vrc-get-vpm/Cargo.toml
vrc-get/build.rs

chore: reimplemnent bootstrapper with rust

---

CHANGELOG.md
vrc-get-vpm/Cargo.toml
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/environment/litedb.rs
vrc-get-vpm/src/environment/project_management.rs
vrc-get-vpm/src/environment/settings.rs
vrc-get-vpm/src/environment/unity_management.rs
vrc-get-vpm/src/io/mod.rs
vrc-get-vpm/src/io/tokio.rs
vrc-get-vpm/src/lib.rs
vrc-get/Cargo.toml
vrc-get/src/commands/migrate.rs
vrc-get/src/commands/vcc.rs

Unity management

---

CHANGELOG.md
README.md
vrc-get-vpm/src/environment.rs
vrc-get/Cargo.toml

Disable vcc by default

---

CHANGELOG.md
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/environment/uesr_package_collection.rs
vrc-get-vpm/src/lib.rs
vrc-get-vpm/src/repository/local.rs
vrc-get-vpm/src/repository/remote.rs
vrc-get-vpm/src/unity_project/pending_project_changes.rs
vrc-get-vpm/src/version_selector.rs
vrc-get-vpm/tests/common/package_collection.rs
vrc-get/src/commands.rs

feat: add vrc-get i --name <name>

---

CHANGELOG.md
vrc-get-vpm/src/unity_project/add_package.rs
vrc-get-vpm/src/unity_project/pending_project_changes.rs
vrc-get-vpm/src/unity_project/resolve.rs
vrc-get-vpm/tests/add_package_to_project.rs

- Fixed panic when upgrading unused package
- Fixed we can add unused package with `vrc-get upgrade` command. Now error instead.
Fixes #394

Upgrade improvements

---

CHANGELOG.md
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/package_json.rs

feat: check zipSHA256 when using cache

---

vrc-get-litedb/dotnet/vrc-get-litedb.csproj

See https://github.com/dotnet/runtime/issues/95100#issuecomment-1822130573

chore(litedb): IlcGenerateWin32Resources = false

---

CHANGELOG-gui.md
vrc-get-gui/.taurignore
vrc-get-gui/src/commands.rs
vrc-get-gui/web/app/projects/manage/page.tsx
vrc-get-gui/web/lib/bindings.ts
vrc-get-vpm/src/lib.rs
vrc-get-vpm/src/unity_project/call_unity.rs
vrc-get-vpm/src/unity_project/migrate_unity_2022.rs
vrc-get-vpm/src/version/unity_version.rs
vrc-get/src/commands/migrate.rs

feat(gui): migrate 2019 to 2022

---

CHANGELOG.md
vrc-get/src/commands.rs

fix(cli): vrc-get repo add accepts non-existence paths

---

CHANGELOG.md
vrc-get-gui/src/commands.rs
vrc-get-gui/web/lib/bindings.ts
vrc-get-vpm/src/environment/project_management.rs
vrc-get/src/commands.rs
vrc-get/src/commands/migrate.rs

fix(gui,cli): last modified not updated when project is changed

---

README.md

:tada: https://github.com/Homebrew/homebrew-core/pull/164453

docs: simplify brew installation and add more installation

---

vrc-get-gui/src/commands.rs
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/environment/litedb.rs

fix: VCC crashes if vrc-get-gui is opened

---

CHANGELOG-gui.md
vrc-get-gui/web/app/projects/manage/page.tsx
vrc-get-gui/web/components/providers.tsx
vrc-get-gui/web/lib/nop.ts

fix toast and dialog

---

.github/ISSUE_TEMPLATE/01_gui_bug-report.yml
.github/ISSUE_TEMPLATE/02_gui_feature_request.yml
.github/ISSUE_TEMPLATE/03_cli_bug-report.yml
.github/ISSUE_TEMPLATE/04_cli_feature_request.yml

本家VCCのリポジトリと、自分が扱っているにりらみすきー部のissue templateを参考にして作りました。

issueテンプレートの設定

---

CHANGELOG-gui.md
Cargo.lock
vrc-get-gui/Cargo.toml
vrc-get-gui/src/commands.rs
vrc-get-gui/src/logging.rs
vrc-get-gui/src/main.rs
vrc-get-gui/web/app/fonts.ts
vrc-get-gui/web/app/log/page.tsx
vrc-get-gui/web/components/SideBar.tsx
vrc-get-gui/web/package-lock.json
vrc-get-gui/web/package.json
web/lib/bindings.ts

feat(gui): logging

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs
vrc-get-gui/web/app/projects/manage/page.tsx
vrc-get-gui/web/lib/bindings.ts

Upgrade all

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs
vrc-get-gui/web/app/settings/page.tsx
vrc-get-gui/web/lib/bindings.ts

chore(gui): verion information in settings

---

README.md

A pull request to fix some grammar mistakes in README.md

Fix English grammar

---

CHANGELOG.md
vrc-get/src/commands.rs
vrc-get/src/commands/migrate.rs

notice that vrc-get vcc is experimental

---

.github/workflows/ci-gui.yml

ci: rename jobs for gui ci

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/package_json.rs
vrc-get-vpm/tests/reading_project.rs
vrc-get/src/commands.rs

fix(vpm): fails to load package.json with invalid url in url field

---

CHANGELOG-gui.md
vrc-get-gui/src/logging.rs

Fix log file

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs
vrc-get-gui/web/app/projects/manage/page.tsx
vrc-get-gui/web/lib/bindings.ts
vrc-get-gui/web/lib/version.ts
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/environment/settings.rs

Prereleases for gui

---

CHANGELOG-gui.md
vrc-get-gui/web/app/settings/page.tsx
vrc-get-gui/web/components/SideBar.tsx

chore(gui): show version name on the left menu

---

.github/workflows/publish.yml

ci: disable automatic homebrew distribution

---

.github/workflows/ci-gui.yml
.github/workflows/publish-gui.yml
CHANGELOG-gui.md
vrc-get-gui/.gitignore
vrc-get-gui/.taurignore
vrc-get-gui/Cargo.toml
vrc-get-gui/README.md
vrc-get-gui/about.toml
vrc-get-gui/app/settings/licenses/page.tsx
vrc-get-gui/app/settings/licenses/render-client.tsx
vrc-get-gui/app/settings/page.tsx
vrc-get-gui/build.d.ts
vrc-get-gui/lib/licenses.ts
vrc-get-gui/package-lock.json
vrc-get-gui/package.json
vrc-get-gui/scripts/build-license-json.mjs
vrc-get-gui/tsconfig.json

License Page 

---

CHANGELOG-gui.md
vrc-get-gui/src/logging.rs

chore(gui): try to improve logging performance

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx

fix(gui): we can lick upgrade button while installing

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/src/commands.rs

feat(gui): reinstall from gui

---

.github/workflows/publish.yml

ci: publish to homebrew

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/src/commands.rs

fix: worlds SDK and packages are shown even if avatars sdk is installed

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/app/projects/page.tsx
vrc-get-gui/components/providers.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/lib/toastThrownError.ts
vrc-get-gui/src/commands.rs
vrc-get-vpm/src/environment/project_management.rs
vrc-get/src/commands/vcc.rs

Better log toast

---

.github/workflows/ci-gui.yml
.github/workflows/publish-gui.yml
CHANGELOG-gui.md

ci(gui): build universal binary

---

CHANGELOG-gui.md
vrc-get-gui/.eslintrc.json
vrc-get-gui/app/projects/page.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/src/commands.rs

feat(gui): remove project and remove directory

---

CHANGELOG-gui.md
Cargo.lock
vrc-get-gui/Cargo.toml
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/src/commands.rs

feat(gui): migrate a copy

---

CHANGELOG-gui.md
vrc-get-gui/src/logging.rs

chore(gui): use local time for timestamp on the log file

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/page.tsx

chore(gui): make "Remove from List" default color

---

README.md

I've fixed some grammatical errors in README. I've also changed some words and phrases so that readers can easily understand what you want to say.

Fix some phrases and grammatical errors

---

CHANGELOG-gui.md
vrc-get-gui/src/cmd_start.rs
vrc-get-gui/src/commands.rs
vrc-get-gui/src/main.rs

Fix #456 
とりあえず分離されて認識されるようになった

Launch unity correctly

---

.github/ISSUE_TEMPLATE/01_gui_bug-report.yml
.github/ISSUE_TEMPLATE/02_gui_feature_request.yml

issue templateの対象projectを修正

---

CHANGELOG-gui.md
CHANGELOG.md
Cargo.lock
vrc-get-vpm/Cargo.toml
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/environment/repo_holder.rs
vrc-get-vpm/src/environment/settings.rs
vrc-get-vpm/src/repository/remote.rs
vrc-get-vpm/src/utils/mod.rs

Fix invalid repo

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx

chore(gui): Show "Not Selected" instead of "none" if the corresponding repositories are not selected

---

CHANGELOG-gui.md
CHANGELOG.md
Cargo.lock
vrc-get-gui/app/projects/page.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/src/commands.rs
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/lib.rs
vrc-get-vpm/src/repository/remote.rs
vrc-get-vpm/src/traits.rs
vrc-get-vpm/src/unity_project.rs
vrc-get-vpm/src/unity_project/add_package.rs
vrc-get-vpm/src/unity_project/find_legacy_assets.rs
vrc-get-vpm/src/unity_project/migrate_unity_2022.rs
vrc-get-vpm/src/unity_project/migrate_vpm.rs
vrc-get-vpm/src/unity_project/pending_project_changes.rs
vrc-get-vpm/tests/add_package_to_project.rs
vrc-get/Cargo.toml
vrc-get/src/commands.rs
vrc-get/src/commands/migrate.rs

Migrate legacy to VCC

---

.github/workflows/ci-gui.yml
.github/workflows/publish-gui.yml
vrc-get-gui/scripts/build-license-json.mjs

build improvements

---

CHANGELOG-gui.md
CHANGELOG.md
Cargo.lock
vrc-get-vpm/Cargo.toml
vrc-get-vpm/src/environment/unity_management.rs

chore(vpm): load unity hub from registry

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-gui/src/commands.rs
vrc-get-vpm/Cargo.toml
vrc-get-vpm/src/environment/unity_management.rs
vrc-get-vpm/src/lib.rs
vrc-get-vpm/src/unity.rs
vrc-get-vpm/src/unity_hub.rs
vrc-get/src/commands/vcc.rs

Fix unity 2018

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-gui/Tauri.toml
vrc-get-gui/src/commands.rs
vrc-get-gui/src/config.rs
vrc-get-gui/src/logging.rs
vrc-get-gui/src/main.rs
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/environment/vrc_get_settings.rs
vrc-get-vpm/src/io/tokio.rs
vrc-get-vpm/src/utils/save_controller.rs

Preserve Window Size

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx

fix(gui): bad behavior with trying installing the installed version

---

CHANGELOG-gui.md
vrc-get-gui/app/settings/page.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/src/commands.rs

Toggle show prerelease packages

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs

fix(gui): external page can be opened

---

CHANGELOG.md
vrc-get-vpm/src/unity_project/find_legacy_assets.rs
vrc-get-vpm/tests/add_package_to_project.rs

Follow VCC 2.3.0 changes

---

CHANGELOG-gui.md
vrc-get-gui/app/settings/page.tsx

https://x.com/kobi_32768_vrc/status/1774374704385794230?s=20

fix: shown language name is not changed

---

README.md

microsoft/winget-pkgs#146966 is merged!

docs(readme): add install using winget

---

.github/workflows/ci-gui.yml
.github/workflows/ci.yml

ci: include commit hash in ci build

---

CHANGELOG-gui.md
vrc-get-gui/app/log/page.tsx
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/app/projects/page.tsx
vrc-get-gui/app/repositories/page.tsx

Fixed the issue that was caused by the shadow effect of the card wrapping around the table
Fix https://github.com/vrc-get/vrc-get/issues/671

Fix issue #671 Project List corder design

---

CHANGELOG-gui.md
vrc-get-gui/app/settings/page.tsx

Fixed it by using the VStack and HNavBar layout components to match the other pages design
Fixes https://github.com/vrc-get/vrc-get/issues/703

Fixes issue #703 Settings Title card is different

---

CHANGELOG-gui.md

I fixed some English mistakes and one missing link until 0.1.0-beta.14.

Fixed some mistakes in CHANGELOG-gui

---

CHANGELOG-gui.md
vrc-get-gui/src/logging.rs

feat(gui): remove old logs

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/page.tsx
vrc-get-gui/app/settings/page.tsx

Fixed the issue by forcing the flex settings for the input and button fields
https://github.com/vrc-get/vrc-get/issues/668

Fix issue 668 Project Location Alignement issue

---

CONTRIBUTING.md

As i had trouble myself to get started in the project, i wanted to suggest a little contributing doc reminding of the system requirements to get setup for the project.

Add initial Contributing proposal

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/page.tsx

Cleaned loading card for Project Page.
Fixes https://github.com/vrc-get/vrc-get/issues/637
We may need a proper way to design those pages as we seem to have the same structure in most of them.

Cleaned loading card for Project Page

---

vrc-get-litedb/README.md
vrc-get-vpm/README.md

Fix [vrc-get-litedb/README.md](https://github.com/vrc-get/vrc-get/compare/master...lu-na-r:vrc-get:fix-docs?expand=1#diff-ffa7ccbf94b1eb480ad3d27aab0fbd6f0a09ae9f8566beb0dde0cbc8d851de93) and [vrc-get-vpm/README.md](https://github.com/vrc-get/vrc-get/compare/master...lu-na-r:vrc-get:fix-docs?expand=1#diff-19582fce93c7e15ff08113bbb49dcd460ac482d1aad8b0e8a10dc5ca36c6d5c0)

Fix some documentations

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/page.tsx

chore(gui): star instead of check for favorite row

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx

chore(gui): move upgrade all button to front

---

CHANGELOG-gui.md
vrc-get-gui/app/settings/page.tsx
vrc-get-gui/locales/en.json5
vrc-get-gui/locales/ja.json5

feat(gui): check for updates button on the settings page

---

CHANGELOG-gui.md
vrc-get-gui/components/SideBar.tsx
vrc-get-gui/locales/en.json5
vrc-get-gui/locales/ja.json5

chore(gui): click version name to copy version name

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs

fix: window size is not saved on cmd+q

---

CHANGELOG-gui.md
vrc-get-vpm/src/environment/project_management.rs
vrc-get-vpm/src/environment/settings.rs

fix: panic with a relative path

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs

fix: Update last modified on open Unity not working

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-vpm/src/unity_project/add_package.rs
vrc-get-vpm/src/unity_project/package_resolution.rs
vrc-get-vpm/src/unity_project/resolve.rs
vrc-get-vpm/tests/add_package_to_project.rs

chore: improve the process with unlocked packages

---

CHANGELOG-gui.md
Cargo.lock
vrc-get-gui/Cargo.toml
vrc-get-gui/src/main.rs

fix: multiple instances can be launched

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs
vrc-get-gui/src/main.rs

fix: bad behaviors with minimizing the window

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/lib/backup-project.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/lib/call-async-command.ts
vrc-get-gui/src/commands.rs
vrc-get-gui/src/commands/async_command.rs

Fixes #792
in addition, this refactors async operation

Error if no backup folder

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs
vrc-get-gui/src/config.rs

feat(gui): save fullscreen status

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx

chore(gui): improve menu bar for narrow windows

---

vrc-get-gui/locales/zh_cn.json5

chore(gui)(zh_cn): fix incorrect variable placeholders

---

CHANGELOG-gui.md
vrc-get-gui/components/SideBar.tsx

Swapped Repositories and Settings position in sidebar

---

CHANGELOG-gui.md
vrc-get-gui/locales/de.json5

Added translation #819 
```
80    "projects:manage:toast:selected packages installed": "Ausgewählte Pakete wurden installiert.",
81    "projects:manage:toast:selected packages removed": "Ausgewählte Pakete wurden entfernt.",
```

German translation: Bulk messages #819

---

CHANGELOG-gui.md
Cargo.lock
vrc-get-gui/Cargo.toml
vrc-get-gui/src/main.rs

feat: add panic handler that outputs to the log instead of stderr

---

vrc-get-gui/locales/ja.json5

chore(gui/ja): update locale

---

.github/scripts/localization-updates.js

This adds configuration for #860

ci: add configuration for German Localization updates

---

vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/components/SearchBox.tsx

This PR makes two UI enhancements:
1. The search input's placeholder text is now always visible, improving intuitiveness.
2. The 'suggest unity migrate' text is vertically centered, ensuring consistency across the UI.

Improve Visibility of Search Placeholder and Vertical Alignment of Suggestion Text

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/page.tsx
vrc-get-gui/locales/en.json5
vrc-get-gui/locales/ja.json5

feat(gui): add project display type "sdk2"

---

.github/scripts/localization-updates.js

This adds configuration for #888

ci: add configuration for Simplified Chinese updates

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-vpm/src/unity_project/find_legacy_assets.rs
vrc-get-vpm/tests/add_package_to_project.rs

chore: follow VCC 2.3.0 beta.3 VPM changes

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs

fix: we cannot see packages from newly added repository just after adding repository

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-vpm/src/lib.rs

chore: update recommended unity version to 2022

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/locales/en.json5
vrc-get-gui/src/commands.rs
vrc-get-vpm/src/unity_project.rs
vrc-get-vpm/src/unity_project/resolve.rs

Resolve suggestion

---

CHANGELOG-gui.md
vrc-get-gui/templates/avatars-2022/ProjectSettings/ProjectSettings.asset
vrc-get-gui/templates/avatars-2022/ProjectSettings/ProjectVersion.txt
vrc-get-gui/templates/worlds-2022/ProjectSettings/ProjectSettings.asset
vrc-get-gui/templates/worlds-2022/ProjectSettings/ProjectVersion.txt

chore: upgrade template unity version to 2022.3.22f1

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/app/projects/manage/unity-migration.tsx
vrc-get-gui/src/commands.rs

Fix patch migration not window updated

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs

fix(gui): vcc connection will be kept after opening the settings page

---

CHANGELOG-gui.md
vrc-get-vpm/src/unity_project/resolve.rs

fix https://misskey.niri.la/notes/9t6uro4ocz

fix: resolve needed check ignores legacy packages

---

CHANGELOG-gui.md
CHANGELOG.md
Cargo.lock
vrc-get-vpm/Cargo.toml
vrc-get-vpm/src/repository/remote.rs

feat: support bad repositories more

---

vrc-get-gui/locales/en.json5

https://github.com/vrc-get/vrc-get/discussions/894#discussioncomment-9422107

"Custom" to "Custom Template"

---

CHANGELOG-gui.md
vrc-get-gui/app/layout.tsx
vrc-get-gui/app/log/page.tsx
vrc-get-gui/components/providers.tsx
vrc-get-gui/tailwind.config.ts

stop bundleing font files and use `system-ui`, and set lang attribute based on selected language.

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs

fix(gui): last modified is not updated on opening unity

---

CHANGELOG-gui.md
vrc-get-gui/app/log/page.tsx
vrc-get-gui/tsconfig.json

chore(gui): make ALCOM does work with ES2020

---

.github/workflows/labeler.yml

ci: use github app token for labeler

---

vrc-get-gui/lib/use-open-unity.tsx
vrc-get-gui/locales/en.json5
vrc-get-gui/locales/ja.json5

I would like to add unity version info to unity not found toast like #988 dialog.

chore(i18n): add unity version info for unity not found toast

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx

feat(gui): make package name gray-outed if not installed

---

CHANGELOG-gui.md
vrc-get-gui/Tauri.toml

Reverts vrc-get/vrc-get#976
Workarounds #1020 tauri-apps/tauri#9836

Revert "feat: allow users to install machine-wide"

---

CHANGELOG-gui.md
vrc-get-vpm/src/environment/unity_management.rs
vrc-get-vpm/src/version/unity_version.rs

fix: incompatibility with unity 2018 by VCC

---

CHANGELOG-gui.md
vrc-get-gui/app/globals.css
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/app/settings/page.tsx
vrc-get-gui/app/settings/palette/page.tsx
vrc-get-gui/components/SideBar.tsx
vrc-get-gui/components/providers.tsx
vrc-get-gui/components/ui/button.tsx

chore: color themes

---

.github/workflows/ci-gui.yml

ci: enable devtools feature for ci builds of ALCOM

---

vrc-get-gui/locales/de.json5

Adds german translation for:
```
projects:manage:toast:the package has newer latest with incompatible unity
projects:manage:toast:some package has newer latest with incompatible unity
projects:manage:tooltip:incompatible with unity
```

chore(i18n/de): add keys for #1046

---

vrc-get-gui/components/providers.tsx
vrc-get-gui/lib/i18n.ts
vrc-get-gui/src/commands.rs
vrc-get-gui/src/config.rs

fix: early loading locale and theme with query parameter

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx

fix: incompatible latest notice is not implemented for bulk upgrade

---

CHANGELOG-gui.md
vrc-get-gui/src/os_windows.rs

fix: crash on windows while checking unity

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-gui/src/commands.rs
vrc-get-vpm/src/environment.rs
vrc-get-vpm/src/environment/project_management.rs
vrc-get-vpm/src/environment/unity_management.rs
vrc-get-vpm/src/utils/mod.rs
vrc-get/src/commands.rs
vrc-get/src/commands/vcc.rs

Unity project management fixes

---

CHANGELOG-gui.md
vrc-get-gui/lib/use-unity-selector-dialog.tsx

fix(gui): unity selector radio button does not work well

---

vrc-get-gui/app/repositories/page.tsx

refactor(gui): use useId

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx

chore(gui): show package display name on uninstalled toast

---

vrc-get-litedb/build.rs
vrc-get-litedb/build_target_info.rs

build(litedb): disable bundle for ld compatibility

---

vrc-get-gui/components/layout.tsx

Fixes #816
skipping changelog since this is small ui fixes

fix: navvar width

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/manage/page.tsx

Improve Search Performance with not triggering render on new matching package is exists
Fixes #1120

chore: improve performance of search on package list page

---

CHANGELOG-gui.md
vrc-get-gui/app/settings/page.tsx
vrc-get-gui/locales/en.json5

feat: open project / backup location

---

vrc-get-gui/app/globals.css

fix: close cross on toast is invisible with dark theme

---

vrc-get-gui/app/globals.css
vrc-get-gui/app/layout.tsx
vrc-get-gui/app/log/page.tsx
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/app/projects/manage/unity-migration.tsx
vrc-get-gui/app/projects/page.tsx
vrc-get-gui/app/repositories/page.tsx
vrc-get-gui/app/settings/licenses/render-client.tsx
vrc-get-gui/app/settings/page.tsx
vrc-get-gui/app/settings/palette/page.tsx
vrc-get-gui/components/SideBar.tsx
vrc-get-gui/components/ui/scroll-area.tsx
vrc-get-gui/package-lock.json
vrc-get-gui/package.json

Fixes #1132
I could not figure out how should I use ScrollView inside dialog so scrolls in dialog are not changed. I'll make another issue

Scroll bar dark mode

---

CHANGELOG-gui.md
vrc-get-gui/app/projects/create-project.tsx
vrc-get-gui/app/projects/manage/package-list-card.tsx
vrc-get-gui/app/projects/manage/page.tsx
vrc-get-gui/app/projects/page.tsx
vrc-get-gui/app/projects/project-row.tsx
vrc-get-gui/app/repositories/page.tsx
vrc-get-gui/components/ReorderableList.tsx
vrc-get-gui/components/SearchBox.tsx
vrc-get-gui/components/SideBar.tsx
vrc-get-gui/package-lock.json
vrc-get-gui/package.json

Fixes https://github.com/vrc-get/vrc-get/issues/1129
What do you think?
From my test, it is safe to uninstall the heroicons package.
Please do so if you end up using this, I am not sure if I did the uninstallation correctly.

chore: Move from heroicons to lucide-react

---

CHANGELOG-gui.md
vrc-get-gui/package-lock.json

Fixes #1176
The Tooltip does not use [`disableOutsidePointerEvents` feature of `react-dismissable-layer`](https://github.com/radix-ui/primitives/blob/7e8f72011dc6b1fbdf07320eeeb20e6b5a7a9d97/packages/react/tooltip/src/Tooltip.tsx#L527C9-L527C36) this works as a solution

fix: fix ui freeze by dedup react-dismissable-layer

---

vrc-get-gui/Tauri.toml
vrc-get-gui/package.json

Many projects uses 3000 so in my PC, port 3000 is very very conflicting and would cause many problems so I changed port number for vrc-get

build: change dev server port number

---

vrc-get-gui/README.md

docs: add note that we require the latest version of rust and cargo-about

---

vrc-get-gui/locales/de.json5

Added
```
settings:appearance
check update:dialog:relaunching...
```

chore(l10n): [de] update locale

---

vrc-get-gui/app/(setup)/setup/finish/page.tsx

Fix https://github.com/vrc-get/vrc-get/pull/1214#issuecomment-2212401939

fix: finish page heading is not localized

---

CHANGELOG-gui.md
vrc-get-gui/src/commands/environment/settings.rs
vrc-get-gui/src/deep_link_support.rs

feat: uninstalling depp link on unchecking use ALCOM for vcc: handling

---

vrc-get-gui/components/SideBar.tsx

Fix https://github.com/vrc-get/vrc-get/pull/1222#issuecomment-2212457999

fix: translation broken in SideBar.tsx

---

.github/scripts/localization-updates.js
CHANGELOG-gui.md
vrc-get-gui/app/(main)/projects/manage/page.tsx
vrc-get-gui/app/(main)/projects/manage/unity-migration.tsx
vrc-get-gui/locales/en.json5
vrc-get-gui/notes-beta.txt
vrc-get-gui/notes.txt

Change unity version

---

CHANGELOG-gui.md
CHANGELOG.md

docs(changelog): #1127 related entry is not on gui changelog

---

CHANGELOG-gui.md
vrc-get-gui/src/os_windows.rs

I thought we should escape twice but it looks we should not

fix: problem with double escape

---

CHANGELOG-gui.md
vrc-get-gui/app/layout.tsx
vrc-get-gui/src/commands/start.rs
vrc-get-gui/src/commands/uri_custom_scheme.rs

fix: loading system config is not working on linux/macos

---

CHANGELOG-gui.md
vrc-get-gui/Tauri.toml
vrc-get-gui/notes-beta.txt
vrc-get-gui/notes.txt
vrc-get-gui/src/deep_link_support.rs

fix: anatawa12 typo

---

CHANGELOG-gui.md
vrc-get-gui/Cargo.toml

fix: not working as SPA

---

CHANGELOG-gui.md
vrc-get-gui/src/commands/environment/projects.rs
vrc-get-gui/src/commands/project.rs
vrc-get-gui/src/config.rs
vrc-get-vpm/src/io/mod.rs
vrc-get-vpm/src/io/tokio.rs
vrc-get-vpm/src/unity_project/migrate_vpm.rs
vrc-get-vpm/src/utils/save_controller.rs
vrc-get-vpm/tests/common/virtual_file_system.rs

Recover from corrupted config file

---

.github/dependabot.yml
vrc-get-gui/package.json

build: configure dependabot groups

---

vrc-get-gui/Cargo.toml
vrc-get-vpm/src/unity_project.rs

lint: fix lint warnings added in rust 1.80

---

vrc-get-vpm/src/unity_project/add_package.rs

fix: outdated `do_add_package_request` reference

---

CHANGELOG-gui.md
vrc-get-gui/Tauri.toml
vrc-get-gui/installer.nsi

registory key migration

---

CHANGELOG-gui.md
vrc-get-gui/src/os_linux.rs

chore: remove AppImage paths from all environment variables

---

vrc-get-gui/src/main.rs

fix: panic with ChangesState

---

CHANGELOG-gui.md
vrc-get-gui/src/commands/start.rs

chore: use maximized on linux

---

vrc-get-gui/lib/global-info.ts

fix: default command-line arguments edit window default value is empty

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/projects/manage/page-context.tsx

fix: tooltips on the package list were not working

---

.github/workflows/ci-gui.yml
.github/workflows/publish-gui.yml
Cargo.lock
Cargo.toml
vrc-get-gui/Cargo.toml
vrc-get-gui/package-lock.json
vrc-get-gui/package.json

Bump deps (stable tauri v2 rc)

---

vrc-get-gui/locales/de.json5
vrc-get-gui/locales/en.json5
vrc-get-gui/locales/fr.json5
vrc-get-gui/locales/ja.json5
vrc-get-gui/locales/zh_hans.json5

chore(l10n): [*] remove unused keys

---

CHANGELOG-gui.md
vrc-get-gui/src/logging.rs

chore: move vrc-get-logs to vrc-get/gui-logs

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/projects/manage/page.tsx
vrc-get-gui/src/commands/project.rs

fix: environment version mismatch error after resolve in some case

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs
vrc-get-gui/src/commands/project.rs
vrc-get-vpm/src/unity_project.rs

fix: already as locked error for multiple install is not localized

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/log/page.tsx
vrc-get-gui/app/(main)/settings/page.tsx
vrc-get-gui/components/ScrollPageContainer.tsx
vrc-get-gui/lib/global-info.ts
vrc-get-gui/locales/en.json5
vrc-get-gui/src/commands.rs
vrc-get-gui/src/commands/uri_custom_scheme.rs

open location buttons

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/log/log-list-card.tsx
vrc-get-gui/app/(main)/log/page.tsx
vrc-get-gui/locales/en.json5
vrc-get-gui/locales/zh_hans.json5

feat(gui): logs page overhaul

---

vrc-get-gui/app/(main)/log/log-list-card.tsx

chore(gui): logs page minor improvement

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/log/log-list-card.tsx
vrc-get-gui/app/(main)/projects/manage/package-list-card.tsx
vrc-get-gui/app/(main)/projects/page.tsx
vrc-get-gui/biome.jsonc
vrc-get-gui/components/SearchBox.tsx
vrc-get-gui/components/providers.tsx
vrc-get-gui/lib/events.ts

Ctrl + F improvements

---

CHANGELOG-gui.md
vrc-get-gui/lib/os.ts

fix: the project path is shown instead of name

---

vrc-get-gui/locales/ja.json5

プロジェクト作成時のマルチバイト文字警告に、"半角英数字等ではない文字"という補足を追加してみました。
問題ないか意見を聞きたいです。

chore(l10n): [ja] update locale ja

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-gui/app/(main)/projects/manage/unity-migration.tsx
vrc-get-gui/app/(main)/projects/project-row.tsx
vrc-get-gui/locales/en.json5
vrc-get-vpm/src/unity_project/migrate_unity_2022.rs
vrc-get-vpm/src/unity_project/migrate_vpm.rs
vrc-get/src/commands/migrate.rs

migration features are no longer experimental

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/projects/manage/unity-migration.tsx
vrc-get-gui/app/(main)/projects/project-row.tsx
vrc-get-gui/lib/backup-project.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/locales/en.json5
vrc-get-gui/src/commands/async_command.rs
vrc-get-gui/src/commands/environment/projects.rs
vrc-get-gui/src/commands/project.rs
vrc-get-gui/src/utils.rs

Backup and Migration improvements

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/packages/repositories/page.tsx
vrc-get-gui/app/(main)/packages/repositories/use-add-repository.tsx
vrc-get-gui/src/deep_link_support.rs

fix: clicking add repository link will close existing adding repository dialog

---

CHANGELOG-gui.md
vrc-get-vpm/src/unity_project/add_package.rs
vrc-get-vpm/src/unity_project/package_resolution.rs

fix: allow installing locked package with unlocked directory

---

vrc-get-gui/locales/ja.json5

partially related: Comments of https://github.com/vrc-get/vrc-get/pull/1561

chore(l10n): [ja] update locale

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-vpm/src/unity_project/find_legacy_assets.rs
vrc-get-vpm/src/unity_project/pending_project_changes.rs

Skip legacy search with upgrade or reinstall

---

vrc-get-gui/locales/zh_hans.json5

The lonelyicer changes were merged. It is recommended to merge lonelyicer pull requests first.
https://github.com/vrc-get/vrc-get/pull/1567

chore(l10n): [zh_Hans] update locale

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/projects/project-row.tsx

chore: show gray star for non-favorite projects

---

.github/workflows/ci.yml
vrc-get-litedb/src/connection_string.rs
vrc-get-vpm/src/package_manifest/yank_state.rs
vrc-get-vpm/src/repository/remote.rs
vrc-get-vpm/src/unity_project/package_resolution.rs
vrc-get-vpm/src/unity_project/pending_project_changes.rs
vrc-get-vpm/src/utils/crlf_json_formatter.rs
vrc-get-vpm/src/utils/deup_deserializer.rs
vrc-get-vpm/src/version/parsing_buf.rs
vrc-get-vpm/src/version_selector.rs
vrc-get/src/commands.rs
vrc-get/src/commands/migrate.rs

ci: exclude litedb from testing

---

CHANGELOG-gui.md
vrc-get-gui/src/commands/project.rs
vrc-get-gui/src/utils.rs

fix: backup name for projects containing dot is not correct

---

CHANGELOG-gui.md
vrc-get-gui/src/commands/environment/projects.rs

fix: error if the project path is "C:"

---

CHANGELOG-gui.md
vrc-get-vpm/src/utils/mod.rs

Add log for investigating #1617

chore: more error information for http request errors

---

CHANGELOG-gui.md
vrc-get-gui/locales/en.json5
vrc-get-gui/src/commands.rs
vrc-get-gui/src/commands/environment/projects.rs
vrc-get-gui/src/commands/project.rs
vrc-get-gui/src/commands/util.rs

feat: better error message for missing drive

---

CHANGELOG-gui.md
vrc-get-gui/src/commands.rs

chore: remove -debugCodeOptimization from default arguments

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-vpm/src/unity_project/package_resolution.rs
vrc-get-vpm/src/unity_project/resolve.rs
vrc-get-vpm/src/version/mod.rs
vrc-get-vpm/src/version/range.rs
vrc-get-vpm/src/version_selector.rs

chore: prefer a stable version over prerelease

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/projects/create-project.tsx
vrc-get-gui/src/commands/environment/projects.rs

Add new project to list before resolving packages

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/projects/manage/use-package-change.tsx
vrc-get-gui/components/ExternalLink.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/lib/errors.ts
vrc-get-gui/lib/i18n.ts
vrc-get-gui/lib/toast.ts
vrc-get-gui/locales/en.json5
vrc-get-gui/src/commands.rs
vrc-get-vpm/src/unity_project/add_package.rs
vrc-get-vpm/src/unity_project/package_resolution.rs
vrc-get-vpm/src/unity_project/reinstall.rs
vrc-get-vpm/src/unity_project/resolve.rs
vrc-get-vpm/tests/add_package_to_project.rs

Better not found error

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/layout.tsx
vrc-get-gui/app/(main)/packages/repositories/page.tsx
vrc-get-gui/app/(main)/packages/user-packages/page.tsx
vrc-get-gui/lib/prev-page.ts

chore: improve page change animation with repositories pages

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/projects/manage/use-package-change.tsx

chore: add space between missing package list and message

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/dev-palette/page.tsx
vrc-get-gui/app/(main)/log/page.tsx
vrc-get-gui/app/(main)/packages/repositories/page.tsx
vrc-get-gui/app/(main)/packages/tab-selector.tsx
vrc-get-gui/app/(main)/packages/user-packages/page.tsx
vrc-get-gui/app/(main)/projects/manage/page.tsx
vrc-get-gui/app/(main)/projects/page.tsx
vrc-get-gui/app/(main)/settings/page.tsx
vrc-get-gui/components/layout.tsx

chore: improve header behavior with thiner window

---

vrc-get-gui/src/commands.rs

chore: show less message for check for update failure

---

vrc-get-gui/app/(main)/dev-palette/page.tsx
vrc-get-gui/lib/toast.ts

Fix #1801 
Fixes bug in beta so no changelog

fix: toast with markup shown oddly

---

CHANGELOG-gui.md
vrc-get-gui/app/(setup)/setup/unity-hub/page.tsx
vrc-get-gui/locales/de.json5
vrc-get-gui/locales/en.json5
vrc-get-gui/locales/fr.json5
vrc-get-gui/locales/ja.json5
vrc-get-gui/locales/zh_hans.json5
vrc-get-gui/locales/zh_hant.json5

fix: link to unity hub is hardcoded to the Japanese version

---

CHANGELOG-gui.md
vrc-get-vpm/src/environment/project_management.rs

fix: support "UnknownUnityVersion"

---

CHANGELOG-gui.md
vrc-get-gui/app/(main)/packages/repositories/use-import-repositories.tsx

fix(gui): correct success toast message for adding a repositories

---

vrc-get-gui/src/commands.rs
vrc-get-gui/src/commands/environment/projects.rs

rust 1.84.0 added some lints. this fixes those lints

style: fix new clippy lints

---

vrc-get-gui/build.rs

I forgot to push this in 1.0.0

fix: failed to build without git

---

CHANGELOG-gui.md
vrc-get-gui/src/commands/project.rs

fix: Backup time now use local time instead of UTC

---

CHANGELOG-gui.md
vrc-get-gui/templates/worlds-2019.4.31f1/ProjectSettings/InputManager.asset
vrc-get-gui/templates/worlds-2022.3.22f1/ProjectSettings/InputManager.asset
vrc-get-gui/templates/worlds-2022.3.6f1/ProjectSettings/InputManager.asset

fix: world template lacks input manager settings

---

vrc-get-gui/app/globals.css

fix: system dark mode

---

CHANGELOG-gui.md
Cargo.lock
vrc-get-gui/Cargo.toml
vrc-get-gui/src/os_windows.rs

feat: enhance os info for windows

---

vrc-get-gui/app/__root.tsx

fix: tanstack router devtools location

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-vpm/src/unity_hub/find_unity_from_unity_hub_logic.rs

fix: loading editors from editors-v2.json is broken

---

CHANGELOG-gui.md
CHANGELOG.md
Cargo.lock
vrc-get-gui/src/commands.rs
vrc-get-gui/src/commands/environment/projects.rs
vrc-get-gui/src/commands/environment/settings.rs
vrc-get-gui/src/commands/project.rs
vrc-get-vpm/Cargo.toml
vrc-get-vpm/src/environment/litedb.rs
vrc-get-vpm/src/environment/project_management.rs
vrc-get-vpm/src/environment/settings.rs
vrc-get-vpm/src/environment/unity_management.rs
vrc-get-vpm/src/io/mod.rs
vrc-get-vpm/src/io/tokio.rs
vrc-get-vpm/tests/common/virtual_file_system.rs
vrc-get/src/commands.rs
vrc-get/src/commands/migrate.rs
vrc-get/src/commands/vcc.rs

Fix #376  again
Fix #1990
Fix #1992
Fix #1993

feat: use newer litedb crate

---

CHANGELOG-gui.md
CHANGELOG.md
Cargo.lock
vrc-get-gui/Cargo.toml
vrc-get-gui/src/commands/environment/packages.rs
vrc-get-gui/src/commands/environment/projects.rs
vrc-get-gui/vite.config.ts

feat: select multiple folders for adding project / user packages

---

CHANGELOG-gui.md
Cargo.lock
vrc-get-vpm/Cargo.toml
vrc-get-vpm/src/environment/litedb.rs

Fixing issue reported in #2036

fix: error if there is no vcc.liteDb file

---

CHANGELOG-gui.md
vrc-get-gui/app/_main/projects/manage/-package-list-card.tsx
vrc-get-gui/components/ScrollableCardTable.tsx
vrc-get-gui/components/ui/scroll-area.tsx

fix: layout shift on select package on manage packages card

---

vrc-get-gui/app/_main/packages/repositories/index.tsx

fix: unable to remove repository

---

vrc-get-gui/app/_main/projects/-project-row.tsx
vrc-get-gui/app/_main/projects/manage/index.tsx
vrc-get-gui/components/OpenUnityButton.tsx

Tiny UX improvements; no changelog

feat: prevent double-launching unity by double-clicking open unity button

---

CHANGELOG-gui.md
vrc-get-gui/app/_main/projects/manage/index.tsx

fix: unable to change the unity version from "unknown"

---

CHANGELOG-gui.md
vrc-get-gui/app/_main/projects/manage/-use-package-change.tsx
vrc-get-gui/lib/bindings.ts
vrc-get-gui/src/commands.rs
vrc-get-vpm/src/unity_project/add_package.rs
vrc-get-vpm/src/unity_project/package_resolution.rs
vrc-get-vpm/src/unity_project/reinstall.rs
vrc-get-vpm/src/unity_project/resolve.rs
vrc-get-vpm/src/version/range.rs
vrc-get-vpm/tests/add_package_to_project.rs

feat: show request version range in the missing dependencies dialog

---

vrc-get-gui/locales/de.json5

Added new keys and updated wording on others.

chore(l10n): [de_DE] update locale

---

vrc-get-gui/app/_main/projects/manage/-package-list-card.tsx

Fix #2191
minor ui improvement

chore: do not reset package selection after package list update

---

CHANGELOG-gui.md
vrc-get-gui/src/utils.rs

chore: preserve LastSceneManagerSetup.txt in library for backups / copy projects

---

CHANGELOG-gui.md
vrc-get-gui/src/commands/environment/projects.rs
vrc-get-gui/src/commands/project.rs
vrc-get-gui/src/utils.rs

chore: keep the library directory for copying project

---

CHANGELOG-gui.md
CHANGELOG.md
vrc-get-vpm/src/unity_project/pending_project_changes.rs

fix: failed to restore package that partially failed packages

---

CHANGELOG-gui.md
vrc-get-gui/app/_main/projects/-project-grid-item.tsx
vrc-get-gui/app/_main/projects/-projects-grid-card.tsx
vrc-get-gui/app/_main/projects/manage/index.tsx
vrc-get-gui/locales/de.json5
vrc-get-gui/locales/en.json5
vrc-get-gui/locales/ja.json5
vrc-get-gui/locales/ko.json5
vrc-get-gui/locales/zh_hans.json5

(These should have been separate PRs, sorry.)
- Improve appearance of last modified info on grid
- Now it shows as `Last Modified: 3 days ago` or `最終更新日: 3日前` instead of just `3 days ago` or `3日前`
- Improve UI text gap
- Use gap-1
- Space at the end of strings was ineffective or redundant

Improve appearance of last modified info on grid, and Improve UI text gap

---

CHANGELOG-gui.md
vrc-get-gui/Info.plist

chore: set badge icon of .alcomtemplate files

---

vrc-get-gui/lib/import-templates.tsx

fix: error from browser on instantiating Intl.DateTimeFormat

---

Cargo.lock
vrc-get-vpm/src/environment/litedb.rs

Fixing #2272
no changelog since fix for internal change

fix: different locales can cause a problem in finding a project by path

---

CHANGELOG-gui.md
vrc-get-gui/app/_main/projects/manage/-package-list-card.tsx
vrc-get-gui/app/_main/projects/manage/-page-context.tsx

fix: reinstall button can be clicked while installing package

---

vrc-get-gui/app/_main/projects/manage/-package-list-card.tsx
vrc-get-gui/app/globals.css

chore: try to disable auto anchoring

---

Cargo.lock

chore(deps): update deps

---

vrc-get-gui/src/commands/environment/templates.rs

chore: add a few more logs to template management

---

.github/workflows/ci-gui.yml
.github/workflows/ci.yml

Workaround for tauri-apps/tauri-action#1091 and community/community#163491

ci: set TAURI_BUNDLER_DMG_IGNORE_CI to false

---

.github/workflows/ci-gui.yml
CHANGELOG-gui.md
vrc-get-vpm/src/environment/unity_management.rs

chore: deduplicating unity locations
