src/commands.rs, src/vpm/mod.rs
=> fix: unlocked packages are not supported

src/vpm/mod.rs
=> fix: mark and sweep ignores unlocked packages

vrc-get-vpm/src/environment.rs, vrc-get-vpm/src/environment/empty.rs, vrc-get-vpm/src/traits.rs, vrc-get-vpm/src/unity_project.rs, vrc-get-vpm/src/unity_project/add_package.rs, vrc-get-vpm/src/unity_project/find_legacy_assets.rs, vrc-get-vpm/src/unity_project/pending_project_changes.rs, vrc-get-vpm/src/unity_project/remove_package.rs, vrc-get-vpm/src/unity_project/resolve.rs, vrc-get-vpm/src/unity_project/vpm_manifest.rs, vrc-get/src/commands.rs, vrc-get/src/main.rs
Behavior Changes:
- `vrc-get resolve <package> <version>` is now invalid. it's not expected
- `vrc-get resolve --prerelease` is now invalid. it's not expected
- `vrc-get remove` now confirms user if removing package conflicts with existing packages. (previously errors)
=> Introduce pending project changes

vrc-get/src/commands.rs
=> fix: vrc-get repo packages doesn't accept repo id

vrc-get-vpm/src/unity_project/upm_manifest.rs
Fix https://github.com/bdunderscore/ndmf/actions/runs/7599806460/job/20697245315?pr=125
=> fix: support upm manifest without dependencies

Cargo.lock
Fixes GHSA-8r5v-vm4m-4g25 or RUSTSEC-2024-0003
=> chore(deps): upgrade dependencies

CHANGELOG.md, vrc-get-vpm/src/environment/litedb.rs
=> chore: relax atomic ordering in LiteDbConnectionHolder

Cargo.lock, vrc-get/Cargo.toml
it has vrc-get downgrade which is a new feature
=> chore(cli): bump next version to 1.7.0

CHANGELOG-gui.md, vrc-get-gui/Tauri.toml
=> fix(gui): window name is not vrc-get-gui

CHANGELOG.md, vrc-get-vpm/src/unity_project.rs, vrc-get-vpm/src/unity_project/resolve.rs, vrc-get-vpm/src/unity_project/vpm_manifest.rs
=> fix(vpm): Empty `depeneencies` block of `locked` section in `vpm-manifest.json` is removed

CHANGELOG-gui.md, vrc-get-gui/src/commands.rs
=> fix: migration to 2022 fails with compilation error

vrc-get-gui/locales/en.json5, vrc-get-gui/locales/ja.json5
Add i18n text to "Settings"/ "language".
before:
en: Language
jp: 言語設定(Language)
close #738
=> chore(gui)(ja/en): add i18n text "language"

CHANGELOG-gui.md
Fixed some typos in CHANGELOG-gui.md.
* "localisation" is not wrong in Britain, but you've used American spelling in every context, so I fixed it.
=> Fix CHANGELOG-gui.md

CHANGELOG-gui.md, vrc-get-vpm/src/environment/unity_management.rs
This commit allows the detection method to include binary via [their official](https://docs.unity3d.com/hub/manual/InstallHub.html#install-hub-linux) APT distribution.
=> feat(vrc-get-vpm): add `/opt/unityhub/unityhub` for detection candidate

vrc-get-gui/locales/de.json5
Adds new key `projects:type:sdk2` from #869 to the german translation file.
SDK2 doesn't need translation, so this is just for completions-sake.
Ready to merge.
=> German translation: Add "projects:type:sdk2"

CONTRIBUTING.md, README.md, vrc-get-gui/CONTRIBUTING.md, vrc-get-gui/README.md
Since many tanslator report (to me) that.... they can't find the way to solve the symlinks and git submoduels problem. (because they are unfamiliar with tools like git and didn't find that there was a CONTRIBUTING.md file....)
I made a pull request to add CONTRIBUTING.md link to each README.md. And update the root CONTRIBUTING.md file clone command to make sure that, symlinks is create correctly (instead of a plain text file with file path)
and maybe we need to consider that add a guide for translator to teach them build a develope environment to see translation change real time?
=> docs: add contributing guide link and update clone command

vrc-get-gui/locales/de.json5
Implements vcc scheme dialog translations to german.
```
"settings:vcc scheme": "<code>vcc:</code> Linktyp Zuweisung",
"settings:vcc scheme description": "Der <code>vcc:</code> Linktyp wird verwendet, um VCC-Paketlisten direkt vom Browser aus hinzufügen zu können.<br>Als alternative zu VCC kann ALCOM diese Anfragen annehmen.<br>Unter MacOS geschieht dies automatisch. Andere Betriebssysteme müssen dies manuell festlegen.",
"settings:register vcc scheme": "ALCOM zum öffnen von <code>vcc:</code> Linktypen registrieren",
"settings:toast:vcc scheme installed": "ALCOM wurde als Programm für <code>vcc:</code> Linktypen registriert.",
```
The translation uses Windows German term for those links, which works better in that language.
=> German translation: Add vcc scheme dialog support.

CHANGELOG-gui.md, vrc-get-gui/app/projects/page.tsx, vrc-get-gui/src/config.rs
Fixes #459
よくみたらpackageリストページでうまく実装できてたのでそれを持ってきたらうまく動いた。
=> chore: improve projects page with narrow window

vrc-get-gui/locales/de.json5
Adds keys for the new theme selector.
Using the word Design is more common in German translations.
```
"settings:theme": "Design",
"settings:theme:system": "System",
"settings:theme:light": "Hell",
"settings:theme:dark": "Dunkel",
```
=> chore(i18n/de): Add theme keys

CHANGELOG-gui.md, vrc-get-vpm/src/environment/unity_management.rs
=> fix: invalid unity versions in litedb would cause failing to load the unity list

CHANGELOG-gui.md, vrc-get-gui/src/deep_link_support.rs
=> fix(gui/linux): vcc link installation fails on linux

vrc-get-gui/components/SideBar.tsx
I changed the icon of packages to a more general packages Icon.
Used it in my buddyworks_v2 fork in the past.
You might want to add a NO-CHANGELOG tag for that?
=> chore: changed icon for packages.

CHANGELOG-gui.md, CHANGELOG.md, vrc-get-vpm/src/unity_project/pending_project_changes.rs
=> fix(vpm): fix handling dot underscore files used internally in macOS for resource fork

CHANGELOG-gui.md, vrc-get-gui/locales/en.json5
`"projects:dialog:vpm migrate description": "Migrating project might loose your changes. Please make a backup of your project before migration."`
correct `loose` to `lose`
=> fix: correct typo

CHANGELOG-gui.md, vrc-get-gui/app/(main)/settings/page.tsx
=> fix: opening Templates folder fails if not exists

vrc-get-gui/README.md
Closes #1399 since Mojave is completely unsupported version as of this version support policy.
=> docs: update README for ALCOM, adds Platform Version Policy and remove experimental

vrc-get-gui/package-lock.json, vrc-get-gui/package.json
and this removes parseargs from runtime dependency
Fix #1744
=> fix: tailwind-animate is added as runtime dependency

vrc-get-gui/locales/de.json5, vrc-get-gui/locales/en.json5
The englisch template uses \n for a new string instead of <br/>, resulting in that line break being ignored.
Also new strings for german locale.
=> chore(l10n): [de_DE] update locale and line-break fix for en.

vrc-get-gui/app/_main/projects/manage/index.tsx
「プロジェクトを削除」の文字スタイルが プロジェクト一覧画面 と プロジェクトの管理画面 で異なっていたため、プロジェクト一覧画面 に合わせて修正しました。
=> fix(gui): text style for "remove project"

CHANGELOG-gui.md, vrc-get-vpm/src/environment/litedb.rs
ファイル名の大文字小文字が区別されるシステムでは、 d5da94a3 以降のコミットでALCOMの起動時にNo such file or directory (os error 2)というエラーが発生していました。
これは以前のバージョンでvcc.liteDbという名前で作成していたファイルをvcc.liteDBという名前で読み込もうとしていることが原因です。
ファイルが存在しない場合には新しく生成されるべきだとは思いますが、それはlitedb-rs側の責務だと思うのでこのPRでは特に触っていません。
また、このPRがmasterブランチにマージされてもUnityHubから情報を読み込む時などにlitedb-rs側でpanicが発生しますが、こちらも触れていません。
=> fix: wrong litedb filename

vrc-get-vpm/src/version/unity_version.rs
The logic is not necessary because Unity uses 6000 for unity 6 so we don't have to compare as 5 < 20xx < 6, we just simplty 5 < 20xx < 6000
=> chore: remove unnecessary special handling for unity 6 implemented before Unity 6000 release

.github/workflows/ci-gui.yml, .github/workflows/publish-gui.yml, CHANGELOG-gui.md
To resolve glibc version problem, I changed ubuntu version used for building .deb and appimage to 22.04, which is oldest supported LTS with webkit2gtk 4.1
Closes #1996
Closes #2145
Related #1914
=> ci: use ubuntu-22.04 for building new ALCOM

vrc-get-gui/app/_main/packages/templates/index.tsx, vrc-get-gui/components/ReorderableList.tsx
=> fix: a reorderable list may become empty even if allowEmpty = false

CHANGELOG-gui.md, vrc-get-gui/app/_main/projects/-create-project.tsx, vrc-get-gui/biome.jsonc
Closes #2325
The webview crashes because calling `window.close` broke wry's webview, but calling `window.close` itself is a problem in ALCOM so this fixes the call.
The issue for breaking window on window.close is tauri-apps/tauri#13331
=> Crash on creating project

CHANGELOG-gui.md, vrc-get-gui/app/_main/packages/repositories/-use-add-repository.tsx, vrc-get-gui/app/_main/packages/repositories/-use-import-repositories.tsx, vrc-get-gui/app/_main/packages/repositories/index.tsx, vrc-get-gui/app/_main/packages/templates/index.tsx, vrc-get-gui/app/_main/packages/user-packages/index.tsx, vrc-get-gui/app/_main/projects/-create-project.tsx, vrc-get-gui/app/_main/projects/-project-row.tsx, vrc-get-gui/app/_main/projects/manage/-copy-project.tsx, vrc-get-gui/app/_main/projects/manage/-unity-migration.tsx, vrc-get-gui/app/_main/projects/manage/-use-package-change.tsx, vrc-get-gui/app/_main/projects/manage/index.tsx, vrc-get-gui/app/_main/settings/index.tsx, vrc-get-gui/components/BackupProjectDialog.tsx, vrc-get-gui/components/CheckForUpdateMessage.tsx, vrc-get-gui/components/RemoveProjectDialog.tsx, vrc-get-gui/components/SideBar.tsx, vrc-get-gui/components/unity-selector-dialog.tsx, vrc-get-gui/lib/import-templates.tsx, vrc-get-gui/lib/open-unity.tsx
close #2515
ref: #2516
- `text-muted-foreground`の色指定が機能していなかったため今まで表面化していなかったが、`DialogDescription`は`text-muted-foreground`を指定しており、 #2516 をmergeするとダイアログの大半の色が変化する
- そもそも`DialogDescription`はHeader以下においてDialogの概要を説明するためのコンポーネントであり、contentの全体をwrapするためのコンポーネントではないため、用法が間違っている
- 以上のことから`DialogHeader`以下にない`DialogDescription`を削除した
=> fix: replace some DialogDescription with div in dialog components
